### ISSUE TITLE
Columnas de tutores

### ISSUE THREAD

**Issue by majosesolares** [pcs-unam/pcs-unam.github.io#4]
Agregar a las columnas adscripción, campos de conocimiento (tabla Maestría), líneas de investigación (tabla de Doctorado) y palabras clave. Disponibilidad puede quedar hasta la derecha.

**Comment by rgarcia-herrera** [comment]
https://pypi.org/project/parsedom/

**Comment by majosesolares** [comment]
Indices para campos, líneas, palabras clave y adscripciones. Además buscador.
